---
- name: Setup groups.
  tags:
    - install
    - upgrade-charm
  group: name={{ wsgi_group }} gid=1500

- name: Setup users.
  tags:
    - install
    - upgrade-charm
  user: name={{ wsgi_user }} uid=1500 group={{ wsgi_group }} createhome=no

- name: Install dependencies.
  tags:
    - install
    - upgrade-charm
  apt: pkg={{ item }}
  with_items:
    - unzip

- name: Setup directories.
  tags:
    - config-changed
  file: path={{ item }} state=directory owner={{ wsgi_user }} group={{ wsgi_group }} recurse=yes
  with_items:
    - "{{ application_dir }}"
    - "{{ code_dir }}"
    - "{{ current_code_dir}}"
    - "{{ archives_dir }}"
    - "{{ current_archive_dir }}"
    - "{{ log_dir }}"
    - "{{ local_oopses }}"

- name: Setup logrotation
  tags:
    - install
    - upgrade-charm
  template:
    src: "log-rotate.j2"
    dest: /etc/logrotate.d/click-index
    owner: "{{ wsgi_user }}"
    group: "{{ wsgi_group }}"
    mode: 0644
