- name: Restart wsgi
  # Trigger the wsgi subordinate to restart by changing settings.
  command: >
    relation-set -r {{ item.__relid__ }}
    timestamp={{ ansible_date_time.iso8601_micro }}
  with_items: relations['wsgi-file']
